sharding:
    jdbc:
        datasource:
            names: ds0,ds1

shardingRule:
    tables:
        t_user:
            actualDataNodes: ds${0..1}.t_user${0..1}
            databaseStrategy:
                inline:
                    shardingColumn: id
                    algorithmExpression: ds${user_id % 2}
            tableStrategy:
                inline:
                    shardingColumn: id
                    algorithmExpression: t_user${order_id % 2}
            keyGenerator:
                type: SNOWFLAKE
                column: id

        t_order:
            actualDataNodes: ds${0..1}.t_order${0..1}
            databaseStrategy:
                inline:
                    shardingColumn: user_id
                    algorithmExpression: ds${user_id % 2}
            tableStrategy:
                inline:
                    shardingColumn: order_id
                    algorithmExpression: t_order${order_id % 2}
            keyGenerator:
                type: SNOWFLAKE
                column: order_id
        t_order_item:
            actualDataNodes: ds${0..1}.t_order_item${0..1}
            databaseStrategy:
                inline:
                    shardingColumn: user_id
                    algorithmExpression: ds${user_id % 2}
            tableStrategy:
                inline:
                    shardingColumn: order_id
                    algorithmExpression: t_order_item${order_id % 2}
    bindingTables:
        - t_order,t_order_item
    broadcastTables:
        - t_config

    defaultDataSourceName: ds0
    defaultTableStrategy:
        none:
    defaultKeyGenerator:
        type: SNOWFLAKE
        column: order_id
